[package]
name = "mstm32"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aux7 = { path = "auxiliary" }



[profile.release]
codegen-units = 1
debug = true
lto = true